In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4,5] #1 dimentional array
a  = np.array(list1)

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(5,)

In [6]:
a.min()

1

In [7]:
a.max()

5

In [8]:
a.argmax()  #index of maximum value

4

In [9]:
a.argmin()

0

In [10]:
list2 = [[1,2,3,4],[5,6,7,8]]
b = np.array(list2)

In [11]:
b     #2 dimentinal array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
b.argmax()

7

In [13]:
b.ndim

2

In [14]:
a.ndim

1

In [22]:
list3 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
c = np.array(list3)

In [23]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
c.ndim

3

In [29]:
c.shape

(3, 4)

# indexing and slicing?

In [25]:
a[2] #indexing

3

In [26]:
b[1]

array([5, 6, 7, 8])

In [27]:
c[2]

array([ 9, 10, 11, 12])

In [30]:
c[:,1:3] #slicing , rows, columns

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## functions

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
np.ones(5)*6

array([6., 6., 6., 6., 6.])

In [40]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [41]:
np.linspace(0,10,20) #linearly spaced values

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [43]:
np.random.rand(10) #0 and 1

array([0.18877931, 0.92927094, 0.05432185, 0.80618247, 0.29494947,
       0.55278507, 0.5888229 , 0.62779721, 0.60602254, 0.22155757])

In [59]:
b = np.random.randint(1,100,24)

In [60]:
b

array([ 5, 40, 53, 23, 68, 50, 51, 83, 55, 50, 32, 31,  3, 74, 32, 38, 32,
       43, 22, 77, 62, 73, 18,  8])

In [66]:
np.sort(np.random.randint(1,100,24))

array([ 2,  9, 11, 12, 14, 24, 26, 31, 32, 43, 50, 55, 56, 62, 64, 66, 67,
       67, 85, 88, 90, 91, 95, 95])

In [61]:
b.reshape(6,4)

array([[ 5, 40, 53, 23],
       [68, 50, 51, 83],
       [55, 50, 32, 31],
       [ 3, 74, 32, 38],
       [32, 43, 22, 77],
       [62, 73, 18,  8]])

In [62]:
a*b

ValueError: operands could not be broadcast together with shapes (5,) (24,) 

In [63]:
np.

0.5555